export type BukkuPurchasesBill = {
    contact_code: string;
    supplier: string;
    invoice_no?: string | undefined;
    reference_no: string;
    date: string; // dd/MM/yyyy
    payment_term?: string | undefined;
    due_date?: string | undefined;
    currency?: string | undefined;
    rate?: number | undefined;
    tags?: string | undefined;
    description?: string | undefined;
    product?: string | undefined;
    account: string;
    item_description: string;
    quantity?: number | undefined;
    uom?: string | undefined;
    location?: string | undefined;
    unit_price: number;
    discount?: number | undefined;
    tax?: number | undefined;
    classification_code?: string | undefined;
};

export type BukkuSalesBill = {
    contact_code: string;
    buyer: string;
    invoice_no?: string | undefined;
    reference_no: string;
    date: string; // dd/MM/yyyy
    payment_term?: string | undefined;
    due_date?: string | undefined;
    currency?: string | undefined;
    rate?: number | undefined;
    tags?: string | undefined;
    description?: string | undefined;
    product?: string | undefined;
    account: string;
    item_description: string;
    quantity?: number | undefined;
    uom?: string | undefined;
    location?: string | undefined;
    unit_price: number;
    discount?: number | undefined;
    tax?: number | undefined;
    classification_code?: string | undefined;
};

export type BukkuContacts = {
    contact_code: string;
    update_contact_code?: string | undefined;
    legal_name: string;
    entity_type?: string | undefined;
    other_name?: string | undefined;
    reg_no_type?: string | undefined;
    reg_no?: string | undefined;
    old_reg_no?: string | undefined;
    tin?: string | undefined;
    sst_reg_no?: string | undefined;
    billing_first_name?: string | undefined;
    billing_last_name?: string | undefined;
    shipping_first_name?: string | undefined;
    shipping_last_name?: string | undefined;
    is_customer?: boolean | undefined;
    is_supplier?: boolean | undefined;
    is_employee?: boolean | undefined;
    receivable_account_code?: string | undefined;
    credit_limit?: number | undefined;
    payable_account_code?: string | undefined;
    groups?: string | undefined;
    price_level?: string | undefined;
    contact_no?: string | undefined;
    email_addresses?: string | undefined;
    billing_street?: string | undefined;
    billing_city?: string | undefined;
    billing_state?: string | undefined;
    billing_postcode?: string | undefined;
    billing_country_code?: string | undefined;
    shipping_street?: string | undefined;
    shipping_city?: string | undefined;
    shipping_state?: string | undefined;
    shipping_postcode?: string | undefined;
    shipping_country_code?: string | undefined;
    currency_code?: string | undefined;
    payment_term?: string | undefined;
    income_account_code?: string | undefined;
    expense_account_code?: string | undefined;
    location?: string | undefined;
    tags?: string | undefined;
    myinvois_action?: string | undefined;
    monthly_statement?: boolean | undefined;
    invoice_reminder?: boolean | undefined;
    remarks?: string | undefined;
};